on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

name: CI

jobs:
  test-schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
    - run: npm install
    - run: npm test

  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.setup-matrix.outputs.variants }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up matrix of variants
        id: setup-matrix
        run: |
          variants="$(make print-variants)"
          variants=$(echo "$variants" | jq -R -c '[splits(" ")]')
          echo "variants=$variants" >> $GITHUB_OUTPUT

  test-rules:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJson(needs.setup-matrix.outputs.variants) }}
    runs-on: ubuntu-latest
    env:
      VARIANTS: ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          install: true

      - name: Build image(s)
        run: |
          make build-all

      - name: Test rules
        run: |
          make test-all
